header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.s'

  paths-ignore:
    - bookinfo/kitex_gen/**
    - bookinfo/internal/server/**/wire_gen.go

  comment: on-failure