apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: productpage
    app.kubernetes.io/name: productpage
  name: productpage
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: productpage
    app.kubernetes.io/name: productpage
  type: ClusterIP
