apiVersion: v1
data:
  productpage.yaml: |
    server:
      addr: 0.0.0.0:8081
    reviews:
      endpoint: reviews.default.svc.cluster.local:8082
      enableXDS: true
    details:
      endpoint: details:8084
kind: ConfigMap
metadata:
  name: productpage

