apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: productpage
    app.kubernetes.io/name: productpage
    version: v1
  name: productpage-v1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: productpage
      app.kubernetes.io/name: productpage
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/instance: productpage
        app.kubernetes.io/name: productpage
        version: v1
    spec:
      containers:
      - args:
        - productpage
        - --config=config/productpage.yaml
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: METRICS_LOG_LEVEL
          value: err
        image: cr-cn-beijing.volces.com/coa-samples/bookinfo
        imagePullPolicy: Always
        name: server
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /app/config
          name: config-volume
      restartPolicy: Always
      serviceAccountName: default
      volumes:
      - configMap:
          defaultMode: 420
          name: productpage
        name: config-volume

