apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: reviews
    app.kubernetes.io/name: reviews
  name: reviews-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: reviews
      app.kubernetes.io/name: reviews
      version: v3
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/instance: reviews
        app.kubernetes.io/name: reviews
        version: v3
    spec:
      containers:
      - args:
        - reviews
        - --config=config/reviews.yaml
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: ENABLE_RATINGS
          value: "enable"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CONSUL_HTTP_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: METRICS_LOG_LEVEL
          value: err
        image: cr-cn-beijing.volces.com/coa-samples/bookinfo
        imagePullPolicy: Always
        name: server
        ports:
        - containerPort: 8082
          name: thrift
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /app/config
          name: config-volume
      restartPolicy: Always
      serviceAccountName: default
      volumes:
      - configMap:
          defaultMode: 420
          name: reviews
        name: config-volume

