service:
  name: productpage
  port: 8081

image: cr-cn-beijing.volces.com/coa-samples/bookinfo

upstreamServices:
  reviews:
    endpoints: reviews.default.svc.cluster.local:8082
    enableXDS: true
  details:
    endpoint: details.default.svc.cluster.local:8084
